[package]
#name = "rust-vite-cli"
#version = "0.1.0"
name = "rust-cli"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
